# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171118_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default='None', max_length=255),
        ),
    ]
