# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171122_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
